services:
  db:
    image: postgres:15.2-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ipbMembers
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: